services:
  - type: web
    name: nexcampus-api
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        value: https://wyxkjsxhizkythxpqmzq.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: sb_publishable_oeP8DeFdjOd_LUAnwETCMQ_zhNQ95Sf
      - key: CORS_ORIGINS
        value: "*"
      - key: PORT
        value: 8000